config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  # Route for 'Coming Soon' page
  get '/coming_soon', to: redirect('/coming_soon.html')

  # Spotify authentication callback
  get '/auth/spotify/callback', to: 'users#spotify'

  # Dashboard route
  get 'dashboard', to: 'playlists#dashboard'
  get 'about', to: 'pages#about', as: :about

  # Route for updating position
post '/update_playlist_order', to: 'playlist_songs#update_playlist_order'

  # Resources for playlists and nested playlist_songs
  resources :playlists do
    member do
      get "share/:uuid", to: "playlists#receiver_view", as: :share
      get :preview
      get :confirmation

      # New route for receiver_view
      #get 'receiver_view/:uuid', to: 'playlists#receiver_view', as: :receiver_view
      # Simplified route for receiver_view for development purposes
      get 'receiver_view', to: 'playlists#receiver_view', as: :receiver_view

    end

    resources :playlist_songs do
      get 'manage', on: :collection
    end
  end


  # BEGIN: ed8c6549bwf9
  # Route for creating a new playlist
  post '/playlists', to: 'playlists#create'
  # END: ed8c6549bwf9

end

app/models/playlist_song.rb
class PlaylistSong < ApplicationRecord
  # acts_as_list scope: :playlist
  belongs_to :playlist
  belongs_to :song

  validate :max_songs_limit,  on: :create
  validates :message, length: { maximum: 200 }
  validates :position, uniqueness: { scope: :playlist_id }
  scope :ordered, -> { order(position: :asc) }
  before_create :set_default_position
  private

  def max_songs_limit
    if playlist && playlist.playlist_songs.count >= 12
      errors.add(:playlist, 'the playlist cannot have more than 12 songs')
    end
  end


  def set_default_position
    self.position = (PlaylistSong.where(playlist_id: playlist_id).maximum(:position) || 0) + 1
  end

  # BEGIN: ed8c6549bwf9
  def like(user)
    self.liked_by(user)
  end
  # END: ed8c6549bwf9

end

app/controllers/playlist_songs_controller.rb
class PlaylistSongsController < ApplicationController
  before_action :set_playlist_song, only: [:edit, :update]

  def new
    @playlist = Playlist.find(params[:playlist_id])
    @playlist_song = PlaylistSong.new

    if params[:query].present?
      @tracks = RSpotify::Track.search(params[:query])
    end

    respond_to do |format|
      format.html # Follow regular flow of Rails
      format.text { render partial: "playlist_songs/list", locals: {playlist: @playlist}, formats: [:html] }
    end
  end

  def create
    @playlist = Playlist.find(params[:playlist_id])
    @song = Song.find_or_create_by(spotify_track_id: params[:track_id],
                                  title: params[:track_name],
                                  artist: params[:track_artists_first_name])
    @playlist_song = PlaylistSong.new
    @playlist_song.song = @song
    @playlist_song.playlist = @playlist



    if @playlist_song.save
      redirect_to edit_playlist_playlist_song_path(@playlist, @playlist_song), notice: 'Song was successfully added.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update_playlist_order
    params[:order].each_with_index do |id, index|
      PlaylistSong.where(id: id).update_all(position: index + 1)
    end
    head :ok
  end

  def edit
    @playlist_song = PlaylistSong.find(params[:id])
    @playlist = @playlist_song.playlist
  end

  def update
    @playlist = Playlist.find(params[:playlist_id])
    @playlist_song = PlaylistSong.find(params[:id])

    if @playlist_song.update(playlist_song_params)
      redirect_to manage_playlist_playlist_songs_path(@playlist)
    else
      render :edit
    end
  end

  def destroy
    @playlist_song = PlaylistSong.find(params[:id])
    @playlist_song.destroy
    redirect_to playlist_playlist_songs_path, status: :see_other, notice: 'Song was successfully removed.'
  end

  def manage
    @playlist = Playlist.find_by(id: params[:playlist_id])

    if @playlist
      @playlist_songs = @playlist.playlist_songs.order(:position)
    else
      redirect_to root_path, alert: "Playlist not found"
    end
  end

  # def update_position
  #   item = PlaylistSong.find(params[:id])
  #   item.update(position: params[:new_position])
  #   head :ok
  # end

  def update_position
    item = PlaylistSong.find(params[:id])
    if item.update(position: params[:new_position])
      head :ok
    else
      render json: { error: "Failed to update position" }, status: :unprocessable_entity
    end
  end

  private

  def set_playlist_song
    @playlist_song = PlaylistSong.find(params[:id])
  end

  def playlist_song_params
    params.require(:playlist_song).permit(:message, :position, :song_id,)
  end

  def set_default_position
    self.position ||= playlist.playlist_songs.count + 1
  end
end

app/views/playlist_songs/_list.html.erb
  <div data-search-target="list">
    <% if @tracks %>
        <% @tracks[0..4].each do |track| %>
        <div class="songcards row align-items-center justify-content-center mt-0">
            <div class=" songcards d-flex size justify-content-center mt-0">
              <div class="songcards col-lg-8 col-md-4 col-sm-2">
                <iframe style="border-radius:12px" src="https://open.spotify.com/embed/track/<%=track.id%>?utm_source=generator" width="100%" height="200" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture"></iframe>
              </div>
              <%= simple_form_for [playlist, PlaylistSong.new] do |f|%>
                <%= hidden_field_tag :track_name, track.name %>
                <%= hidden_field_tag :track_id, track.id %>
                <%= hidden_field_tag :track_artists_first_name, track.artists.first.name %>
                <button type="submit" class=" add ms-5">
                <i class="fa-solid fa-plus plus"></i>
                </button>
              <% end %>
            </div>
            </div>
        <% end %>
    <% end %>
  </div>

<!-- f.submit 'safe' -->

app/views/playlist_songs/edit.html.erb
<div class="container" data-controller="validation">
  <div class="row justify-content-center align-items-center mt-5">
    <div class="col-md-8 cardDash p-4 pt-0">

      <h1 class="text-center">Add you personal message to the song</h1>
      <hr class="header-divider">
      <div class="song-details">
        <p><strong>Song:</strong> <%= @playlist_song.song.title %></p>
        <p><strong>Artist:</strong> <%= @playlist_song.song.artist %></p>
      </div>
        <%= simple_form_for [@playlist, @playlist_song] do |f| %>
          <div class="form-group">
            <p><strong>Message:</strong>
            <%= f.text_area :message, placeholder: 'Add your personal message...', class: 'form-control', data: { validation_target: "input_message", action: "keyup->validation#message" } %>
            <p><span data-validation-target="note_message" style=" color: red "></span></p>
          </div>
        <%# <div class="form-group my-3 d-flex justify-content-center"> %>
          <div class="home-start-button">
            <div class="d-flex justify-content-between mb-5">
              <%= link_to ('<i class="fa-solid fa-backward-step"></i>  back ').html_safe, new_playlist_playlist_song_path(@playlist), class: 'tn btn-modern' %>
              <%= f.submit "Update", class: 'start-button' %>
            </div>
            <% end %>
          </div>
        </div>
      </div>
      <div class="home-start-button">

      </div>
  </div>
</div>

app/views/playlist_songs/manage.html.erb
<div class="cardManage">
  <h1 class="manage-title">Manage your Playlist</h1>
  <hr class="header-divider">

  <div class="navigation-buttons home-start-button">
    <%= link_to ('<i class="fa-solid fa-backward-step"></i>  Dashboard ').html_safe, dashboard_path, class: 'btn btn-modern btn-secondary', class:' btn btn-modern' %>
    <%= link_to ('Preview    <i class="fa-solid fa-forward-step"></i>').html_safe, preview_playlist_path(@playlist), class:' btn btn-modern' %>
  </div>

  <div class="manage-container">

    <div class="playlist-layout">
      <p class="ps-2 pb-0 mb-0 pt-0 mt-0 text-center">Playlist Information: </p>
      <div class="playlist-info shadow">
        <h1><%= @playlist.title %></h1>
        <div class="from-to-container">
            <div class="badge badge-from">From:</div>
            <p><%= @playlist.from_name %></p>

            <div class="badge badge-to">To:</div>
            <p><%= @playlist.to_name %></p>
          </div>
        <p class="mt-2"><%= @playlist.general_message %></p>
        <div class="d-flex justify-content-end">
          <%= link_to edit_playlist_path(@playlist), class: 'btn btn-icon' do %>
            <i class="fa-solid fa-pen-to-square"></i>
          <% end %>
        </div>
      </div>

      <%= link_to edit_playlist_path(@playlist), class: 'btn btn-modern edit' do %>
        <i class="fa-solid fa-pen-to-square"></i>
      <% end %>


    </div>

    <p class="manage-subtitle mt-0 pt-0">To rearrange the playlist just use drag and drop</p>

    <%# Playlist Full Warning with Badge %>
      <% if @playlist_songs.count >= 12 %>
        <p class=" badge-warning">Playlist is full!</p>
      <% else %>
        <%= link_to 'Add new Song', new_playlist_playlist_song_path(@playlist), class: 'start-button block mx-auto' %>
      <% end %>

        <%# Grid Layout for Songs %>
      <% if @playlist_songs.any? %>
        <div id="sortable-grid" class="grid-layout">
          <% @playlist_songs.each_with_index do |playlist_song, index| %>
            <div class="grid-item" data-id="<%= playlist_song.id %>">
              <span class="place-number badge"><%= index + 1 %></span>
              <% if playlist_song.message.blank? %>
              <%= link_to "Add a message", edit_playlist_playlist_song_path(@playlist, playlist_song), class: "song-message d-flex justify-content-center add-link" %>
              <% else %>
              <p class="song-message"><%= playlist_song.message.truncate(60) %></p>
              <%end %>
              <p class="song-title"><%= playlist_song.song.title %> <br>by <%= playlist_song.song.artist %></p>
              <%# Edit and Delete Actions with Icons %>
              <%= link_to edit_playlist_playlist_song_path(@playlist, playlist_song), class: 'action-link' do %>
                <i class="fa-solid fa-edit"></i>
              <% end %>
              <%= link_to playlist_playlist_song_path(@playlist, playlist_song), method: :delete, data: { turbo_method: :delete, turbo_confirm: "Are you sure? This will delete the song with your personal message, and CANNOT be reverted!" }, class: 'action-link' do %>
                <i class="fa-solid fa-trash"></i>
              <% end %>
            </div>
          <% end %>
        </div>
      <% else %>
        <p class="no-songs">No songs in this playlist.</p>
      <% end %>


      <%= turbo_stream_from 'sortable-grid' %>

      <%# Existing Script Code Here... %>
        <script>
        // ...existing JavaScript code...
            document.addEventListener('turbo:load', function () {
              const gridElement = document.getElementById('sortable-grid');
          if (gridElement) {
            new Sortable(gridElement, {
              swapThreshold: 0.75,
              swapClass: 'highlight',
              animation: 500,
              ghostClass: 'sortable-ghost',
              onEnd: function(evt) {
                const order = this.toArray();
                fetch('/update_playlist_order', {
                  method: 'POST',
                  headers: {
                    'Content-Type': 'application/json',
                    'X-CSRF-Token': document.querySelector('[name="csrf-token"]').content
                  },
                  body: JSON.stringify({ playlist_id: "<%= @playlist.id %>", order: order })
                }).then(response => {
                  if (response.ok) {
                    console.log('Order updated');
                    updatePlaceNumbers();
                  } else {
                    console.error('Error updating order');
                  }
                });
              }
            });
          }
        });

        function updatePlaceNumbers() {
          const placeNumbers = document.getElementsByClassName('place-number');
          Array.from(placeNumbers).forEach((placeNumber, index) => {
            placeNumber.innerText = index + 1;
          });
        }
      </script>
  </div>
</div>

app/views/playlist_songs/new.html.erb
<div class="container d-flex align-items-center justify-content-center">
  <div class="cardAddSong p-3 mt-2 shadow">
    <div class="home-start-button">
      <%= link_to ('<i class="fa-solid fa-backward-step"></i>  back ').html_safe, manage_playlist_playlist_songs_path(@playlist), class: ' btn btn-modern' %>
    </div>
      <div class="addSong mt-5">
        <div>
          <h1>Add it to your playlist</h1>
        </div>

        <div data-controller="search">
          <%= form_with url: new_playlist_playlist_song_path, method: :get, class: "searchform",
              html: {data: {search_target: "form"}} do |f| %>
            <%= f.text_field :search, placeholder: "Search for a song", value: params[:query], data: {search_target: "input", action: "keyup->search#update"} %>
          <% end %>

          <div class="dropdown">
            <%= render "list", tracks: @tracks, playlist: @playlist %>
          </div>
        </div>
      </div>
  </div>
</div>