config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  # Route for 'Coming Soon' page
  get '/coming_soon', to: redirect('/coming_soon.html')

  # Spotify authentication callback
  get '/auth/spotify/callback', to: 'users#spotify'

  # Dashboard route
  get 'dashboard', to: 'playlists#dashboard'
  get 'about', to: 'pages#about', as: :about

  # Route for updating position
post '/update_playlist_order', to: 'playlist_songs#update_playlist_order'

  # Resources for playlists and nested playlist_songs
  resources :playlists do
    member do
      get "share/:uuid", to: "playlists#receiver_view", as: :share
      get :preview
      get :confirmation

      # New route for receiver_view
      #get 'receiver_view/:uuid', to: 'playlists#receiver_view', as: :receiver_view
      # Simplified route for receiver_view for development purposes
      get 'receiver_view', to: 'playlists#receiver_view', as: :receiver_view

    end

    resources :playlist_songs do
      get 'manage', on: :collection
    end
  end


  # BEGIN: ed8c6549bwf9
  # Route for creating a new playlist
  post '/playlists', to: 'playlists#create'
  # END: ed8c6549bwf9

end

app/models/playlist.rb
class Playlist < ApplicationRecord
  before_create :generate_uuid

  belongs_to :user
  has_many :playlist_songs
  validates :title, presence: true
  validates :title, length: { maximum: 40 }
  validates :general_message, presence: true
  validates :general_message, length: { maximum: 200 }
  validates :from_name, presence: true
  validates :to_name, presence: true

  def generate_uuid
    self.uuid = SecureRandom.uuid
  end
end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController
  before_action :set_playlist, only: [:show, :edit, :update, :destroy, :confirmation, :preview]
  skip_before_action :authenticate_user!, only: [ :index, :show ]

  def index
    @playlists = Playlist.all
  end

  def show
    @playlist = Playlist.find(params[:id])
    @playlist_songs = @playlist.playlist_songs
    @playlist_song = PlaylistSong.new
    @user = @playlist.user
  end

  def dashboard
    @playlists = current_user.playlists
    @playlists = Playlist.where(user: current_user)
    @songs = Song.where(user: current_user)
    @user = current_user
  end

  def new
    @playlist = Playlist.new
  end

  def create
    @playlist = Playlist.new(playlist_params)
    @playlist.user = current_user

    if @playlist.save
      redirect_to manage_playlist_playlist_songs_path(@playlist)
    else
      render :new
    end
  end

  def edit
  end

  def update
    @playlist.update(playlist_params)
    redirect_to manage_playlist_playlist_songs_path(@playlist)
  end

def update_position
  @playlist_song = PlaylistSong.find(params[:id])
  @playlist_song.update(position: params[:position])
end

  def destroy
    @playlist = Playlist.find(params[:id])

    # First, delete all associated playlist_songs
    @playlist.playlist_songs.destroy_all

    # Then, delete the playlist
    @playlist.destroy

    redirect_to dashboard_path, notice: 'Playlist was successfully deleted.'
  end


  def confirmation
    # logic
  end

  def preview
    @playlist_songs = @playlist.playlist_songs.includes(:song)
  end

  def receiver_view
    @playlist = Playlist.find_by(uuid: params[:uuid])
    @playlist_songs = @playlist.playlist_songs if @playlist
  end

  private

  def set_playlist
    @playlist = Playlist.find(params[:id])
  end

  def playlist_params
    params.require(:playlist).permit(:title, :general_message, :from_name, :to_name)
  end
end
def update_position
  @playlist_song = PlaylistSong.find(params[:id])
  @playlist_song.update(position: params[:position])

  head :ok
end

app/views/playlists/_form.html.erb
<div data-controller="validation">
  <%= simple_form_for playlist do |f| %>
    <%= f.input :from_name, placeholder: 'Let the reciever know, who send the playlist' %>
    <%= f.input :to_name, placeholder: 'Who would you like to send the playlist to' %>
    <%= f.input :title, placeholder: 'Give a name to your playlist', input_html: { data: { validation_target: "input_title", action: "keyup->validation#title" } } %>
    <p><span data-validation-target="note_title" style=" color: red "></span></p>
    <%= f.input :general_message, placeholder: 'Send a general message', input_html: { data: { validation_target: "input_message", action: "keyup->validation#message" } }, style: 'color: #8f83a4;' %>
    <p><span data-validation-target="note_message" style=" color: red "></span></p>
    <div class="home-start-button">
      <div class="d-flex justify-content-between mb-5">
        <%= link_to ('<i class="fa-solid fa-backward-step"></i>  back ').html_safe, dashboard_path, class: ' btn btn-modern' %>
        <button type="submit" class="start-button" role="button"><span class="text">Save</span></button>
      </div>
    </div>
  <% end %>
</div>

app/views/playlists/_slider.html.erb
<div class="preview">
  <div class="container">

    <div id="songCarousel" class="carousel slide">
      <div class="carousel-inner">
        <% @playlist_songs.each_with_index do |playlist_song, index| %>
          <div class="carousel-item <%= 'active' if index.zero? %>">
            <div class="d-flex align-items-center justify-content-center mt-3 text-left">
              <div class ="text-left">
                <div class="card">
                  <div class="card-body" style="margin-bottom: 20px;">
                      <div class="card-message" style="margin-bottom: 20px;">
                        <h4 class="underline"><strong>Song#<%= playlist_song.position %></strong><br></h4>
                        <p class="underline"><%= playlist_song.message %></p>
                      </div>
                      <div class="d-flex justify-content-center pb-3">
                        <%= image_tag "cassette.gif", style: 'height: 120px; width:auto;' %>
                      </div>
                      <div class="ps-5 pe-5">
                        <iframe style="border-radius:20px" src="https://open.spotify.com/embed/track/<%=playlist_song.song.spotify_track_id%>?utm_source=generator" width="100%" height="150" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture"></iframe>
                      </div>
                    <!-- You can add other song details as needed -->
                  </div>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>

    <!--
      <div class="d-flex align-items-end justify-content-between mt-3">
        <button class="btn carousel-control-prev" type="button" data-bs-target="#songCarousel" data-bs-slide="prev" style="width: 30px; margin-left: 20px;">
          <i class="fa-solid fa-play fa-flip-horizontal"></i>
          <span class="fa-solid fa-play fa-flip-horizontal" aria-hidden="true"></span>
          <span class="visually-hidden">Previous</span>
        </button>
        <button class="btn carousel-control-next" type="button" data-bs-target="#songCarousel" data-bs-slide="next" style="width: 30px; margin-right: 20px;">
          <i class="fa-solid fa-play"></i>
          <span class="fa-solid fa-play" aria-hidden="true"></span>
          <span class="visually-hidden">Next</span>
        </button>
      </div>
    -->

    <!-- Button Control -->
    <div class="d-flex justify-content-center align-items-center mb-5">
        <button class="btn" type="button" data-bs-target="#songCarousel" data-bs-slide="prev">
        <i class="fa-solid fa-backward icon"></i>
        </button>

        <button class="btn" type="button" data-bs-target="#songCarousel" data-bs-slide="next">
        <i class="fa-solid fa-forward icon"></i>
        </button>
    </div>
  </div>
</div>
<script>
  document.addEventListener("DOMContentLoaded", function () {
    const myCarousel = new bootstrap.Carousel(document.getElementById('songCarousel'), {
      interval: false // Set interval to false to disable automatic sliding
    });
  });
</script>

app/views/playlists/confirmation.html.erb
<div class="gif"></div>
<div class="confirmation mt-2">
  <div class="container d-flex align-items-center justify-content-center mb-4">
    <div class="confDash p-5 shadow">
      <div class="col text-center">
        <div class="mb-2">
          <h1>Thank you for using</h1>
        </div>
        <%= image_tag "logo_white.png", style: 'height: 250px;', class: 'confImg' %>
        <div class="mt-4">
          <h2>Your MIX\MATE has been successfully created!</h2>
        </div>
      </div>
      <div class="col text-center mt-4 rounded-5">
        <div class="home-start-button text-center"> <!-- Add text-center class -->
          <div data-controller="clipboard">
            <%= link_to "SHARE NOW", share_playlist_url(id: @playlist.id, uuid: @playlist.uuid), data: { clipboard_target: "link", action: "click->clipboard#copy" }, class: 'start-button block mx-auto' %>
            <span data-target="clipboard.copiedMessage" style="display: none;">Copied!</span>
          </div>
          <h3>&</h3>
          <b><%= link_to "Create another Playlist", new_playlist_path, class: "btn-modern mt-2" %></b>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/playlists/dashboard.html.erb
<div class="dashBG dashboard">
  <div class="container" data-controller="spotify">
    <div class="cardDash p-5 shadow text-center">

    <!-- Only shown when connected to Spotify -->
      <div data-spotify-target="connect">
        <% if session[:attempted_spotify_connect] %>
          <% if user_signed_in? %>
            <h1>Welcome to you Dashboard, <%= @user.username %>!</h1>
            <p>Spotify Connected! Still having issues?
            <%= link_to 'try again', '/auth/spotify', method: :post, class: "link", style: "color: #5D26C1;" %></p>

            <hr class="header-divider">

            <% if @playlists.any? %>
            <h3 class="mb-3"> Your Playlists </h3>
              <div class="row justify-content-start">
                <% @playlists.each do |playlist| %>
                  <div class="col-lg-4 col-md-6 col-sm-6">
                    <div class="card p-3 mb-4 text-start">
                      <%= link_to manage_playlist_playlist_songs_path(playlist_id: playlist.id) do %>
                      <h4><%= playlist.title.truncate(25) %></h4>
                      <p> <strong>To: </strong><%= playlist.to_name %> </p>
                      <div class="d-flex justify-content-end">
                          <%= link_to ('<i class="fa-solid fa-trash"></i>').html_safe, playlist_path(playlist),  method: :delete,  data: {turbo_method: :delete, turbo_confirm: "Are you sure? This will delete the playlistwith all songs and personal messages, and CANNOT be reverted!"}%>
                        <%= link_to ('<i class="fa-solid fa-pencil"></i>').html_safe, edit_playlist_path(playlist), class: "ms-2" %>
                      </div>
                      <% end %>
                    </div>
                  </div>
                <% end %>
              </div>
            <% else %>
              <p>You don't have any playlists yet.</p>
            <% end %>
            <div class="d-flex align-items-right justify-content-right">
              <%= link_to new_playlist_path, class: "link ms-auto" do %>
                <button class="start-button" role="button"><span class="text">Create New Playlist</span></button>
              <% end %>
            </div>

          <% else %>
            <p>Please <%= link_to 'sign in', new_user_session_path %> to view this page.</p>
          <% end %>

        <% else %>
        <!-- Connect your Spotify Page -->
          <h1 class="text-center pb-3">Let's start!</h1>
          <div class="d-flex justify-content-center">
            <%= link_to '/auth/spotify', method: :post, class: "link pb-3 button-64" do %>
              <i class="fa-brands fa-spotify"></i>
              <span class="text">Connect your Spotify account</span>
            <% end %>
          </div>
            <p class="text-center">If you don't connect with your Spotify, you will only be able to listen to a preview of the songs. If that's okay for you <a href='#' data-action="click->spotify#skip" class="skip">skip here</a></p>

        <% end %>
      </div>

      <!-- Shown when skipped -->
      <div class="d-none" data-spotify-target="dashboard">
        <% if user_signed_in? %>
          <div class="d-flex justify-content-between">
            <h1>Welcome to you Dashboard, <%= @user.username %>!</h1>
             <%= link_to '/auth/spotify', method: :post, class: "link pb-3 button-64" do %>
              <i class="fa-brands fa-spotify"></i>
              <span class="text">Connect your Spotify account</span>
            <% end %>
          </div>

          <hr class="header-divider">

          <% if @playlists.any? %>
          <h3> Your Playlists </h3>
            <div class="row justify-content-start text-start">
              <% @playlists.each do |playlist| %>
                <div class="col-lg-4 col-md-6 col-sm-6">
                  <div class="card p-3 mb-4">
                    <%= link_to manage_playlist_playlist_songs_path(playlist_id: playlist.id) do %>
                    <h4> <%= playlist.title %> </h4>
                    <p> <strong>To: </strong><%= playlist.to_name %> </p>
                    <div class="d-flex justify-content-end">
                        <%= link_to ('<i class="fa-solid fa-trash"></i>').html_safe, playlist_path(playlist),  method: :delete,  data: {turbo_method: :delete, turbo_confirm: "Are you sure? This will delete the playlistwith all songs and personal messages, and CANNOT be reverted!"}%>
                      <%= link_to ('<i class="fa-solid fa-pencil"></i>').html_safe, edit_playlist_path(playlist), class: "ms-2" %>
                    </div>
                    <% end %>
                  </div>
                </div>
              <% end %>
            </div>
          <% else %>
            <p>You don't have any playlists yet.</p>
          <% end %>
          <div class="d-flex align-items-right justify-content-right">
            <%= link_to new_playlist_path, class: "link ms-auto" do %>
              <button class="start-button" role="button"><span class="text">Create New Playlist</span></button>
            <% end %>
          </div>
        <% else %>
          <p>Please <%= link_to 'sign in', new_user_session_path %> to view this page.</p>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/playlists/edit.html.erb
<div class="container edit-playlist-container">
  <div class="edit-playlist-card cardDash p-5 shadow">
    <div class="form">
      
      <span><h1 class="text-center"> Edit your Playlist Information</h1>

      <%= render "form", playlist: @playlist %>
    </div>
  </div>
</div>

app/views/playlists/new.html.erb
<%
=begin%>
 <div class="container">
  <div class="cardDash p-5 shadow">
    <div class="form">
      <h1>Create your Playlist</h1>

      <%= render "form", playlist: @playlist %>
    </div>
  </div>
</div>
<%
=end%>


<div class=" container login-container">
  <div class="login-card">
    <h1 class="text-center">Create your Playlist</h1>
    <%= render "form", playlist: @playlist %>
  </div>
</div>

app/views/playlists/preview.html.erb
<div class="container">
  <div class="preview" data-controller="preview">
    <!-- Move the h1 "Preview" to the top right -->
  <div class="d-flex justify-content-end ">
    <h3 class="badge-preview py-2 px-3 text-bold">PREVIEW</h3>
  </div>


<!-- Wrap up Card-->

  <div class="d-flex justify-content-center">
    <div class="card" data-preview-target="card">
      <div class="card-wrap">
        <h1 class="underline">A MIX/MATE from <%= @playlist.from_name %>:</h1>
        <h2 class="underline"> Title:  <%= @playlist.title %></h2>
        <h3 class="underline">Dear <%= @playlist.to_name %>,</h3>
        <h5 class="underline pt-3"><%= @playlist.general_message %></h5>
        <div class="d-flex justify-content-center">
          <button data-action="click->preview#start" class="btn btn-play"><i class="fa-solid fa-circle-play"></i></button>
        </div>
      </div>
    </div>
  </div>


<!-- Cassette Card -->

  <div class="d-none" data-preview-target="player">
      <%= render "slider" %>
    </div>


<!-- Back- and Done- Button -->


    <div class="home-start-button">
      <div class="d-flex justify-content-between mb-5">
        <h5><%= link_to ('<i class="fa-solid fa-backward-step"></i>  Back ').html_safe, manage_playlist_playlist_songs_path(@playlist), class:' btn btn-modern' %></h5>
        <h5><%= link_to ('Done    <i class="fa-solid fa-forward-step"></i>').html_safe, confirmation_playlist_path(@playlist), class:' btn btn-modern' %></h5>
      </div>
    </div>
  </div>
</div>

app/views/playlists/receiver_view.html.erb
<div class="container">
  <div class="preview" data-controller="preview">

  <!-- Wrap up Card-->

  <div class="d-flex justify-content-center">
    <div class="card" data-preview-target="card">
      <div class="card-wrap">
        <h1 class="underline">A MIX/MATE from <%= @playlist.from_name %>:</h1>
        <h2 class="underline"> Title:  <%= @playlist.title %></h2>
        <h3 class="underline">Dear <%= @playlist.to_name %>,</h3>
        <h5 class="underline pt-3"><%= @playlist.general_message %></h5>
        <div class="d-flex justify-content-center">
          <button data-action="click->preview#start" class="btn btn-play"><i class="fa-solid fa-circle-play"></i></button>
        </div>
      </div>
    </div>
  </div>

<!-- Cassette Card -->

  <div class="d-none" data-preview-target="player">
      <%= render "slider" %>

          <div class="home-start-button mt-2 mb-20">
            <div class="d-flex justify-content-center">
              <%= link_to "Create your own MIX/MATE", root_path, class: "btn btn-modern" %>
            </div>
          </div>
  </div>
  </div>
</div>